# ----------- CONFIGURABLE START -----------
title:            "Allajah's Reservoir"
description:      "Allajah(Rio)'s blog"
url:              http://blog.araya.dev # Site url, without a slash at the end.
signoff:          "Allajah" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-104175258-1
share:            true # Turn on twitter and facebook share buttons
timezone: Asia/Tokyo

links:
  - name:         Posts
    url:          /
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title.html
defaults:
  - values:
      layout: "default"
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jemoji
  - jekyll-feed
