version: "3"
services:
  site:
    command: jekyll serve --draft
    image: jekyll/jekyll:3.6.2
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
